language: python
sudo: required

python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  # to replace with tests
  - python manage.py

deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_API_KEY
  app: $HEROKU_APP_NAME
